# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 08:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20171013_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
