# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20171013_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_length',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
