# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20171013_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='modules',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='renewal_dates',
            new_name='renewal_date',
        ),
    ]
