# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20171013_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('work_phone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('referral_option', models.CharField(max_length=30)),
                ('subscribe_to_notices', models.BooleanField(default=True)),
            ],
        ),
    ]
